version: "3.8"
services:
  db:
    image: mariadb:10.7.3
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=app
      - TZ=UTC
    command: mysqld --default-storage-engine=MyISAM
  php8:
    build:
      context: ./
      dockerfile: php8.Dockerfile
    image: gusdecool/symfony:php8
    ports:
      - 6003:80
      - 6004:443
    volumes:
      - ./symfony:/app
      - composer_cache:/root/.composer/cache
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    depends_on:
      - db
volumes:
  composer_cache:
  yarn_cache:
  db_data:
